name: Checkov
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkov Github Action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.1636.0
        with:
          directory: cdk.out
          soft_fail: true
          external_checks_repos: https://github.com/MaxSloof-Deloitte/checkov_github_action//custom_policies
          skip_check: CKV_AWS_54
