name: Checkov
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Checkov Github Action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: cdk.out
          soft_fail: true
          skip_check: CKV_AWS_54
