name: Checkov
on:
  workflow_call:
    secrets:
      APIGW_KEY:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      repo_complete: ${{ github.repository }}
      workspace_path: ${{ github.workspace }}
      api_key: ${{secrets.APIGW_KEY}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: cdk-templates
          path: cdk.out
      # Checkout the private checkov repo to see whether it is possible to checkout private repos from the same account
      - uses: actions/checkout@v3
        with:
          repository: MaxSloof-Deloitte/private_checkov_github_action
          ref: main
          path: checkov_github_action
      - name: Checkov Github Action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.1844.0
        with:
          directory: ${{ github.workspace }}/cdk.out
          external_checks_dirs: ${{ github.workspace }}/checkov_github_action/custom_policies
          soft_fail: true
          skip_check: CKV_AWS_54
          compact: true
          output_format: json
          config_file: ${{ github.workspace }}/checkov_github_action/ckv_config.yml
          # soft_fail_on: CKV_AWS_18, CKV_AWS_55
          # hard_fail_on:
          # quiet: true
      - name: Upload the Checkov output file
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: checkov-output
          path: results_json.json
      - run: |
          ls
