name: Checkov
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkov Github Action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: cdk.out
          soft_fail: true
          external_checks_git: ${{ github.repository_owner }}/checkov_custom_policy/custom_policies@main
          skip_check: CKV_AWS_54
