name: Checkov
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: demo
      - name: Checkov Github Action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: cdk.out
          external_checks_git: https://github.com/MaxSloof-Deloitte/checkov_custom_policy//custom_policies
