name: Checkov
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Checkov Github Action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: cdk.out
          soft_fail: true
          external_checks_repos: https://github.com/MaxSloof-Deloitte/custom_policies.git
          skip_check: CKV_AWS_54
