name: Checkov
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print repo
        run: echo ${{ github.action_repository }}/.checkov.yml
      - uses: actions/checkout@v3
        with:
          ref: demo
      - name: Checkov Github Action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: cdk.out
          config_file: ${{ github.action_repository }}/.checkov.yml
